<?php

namespace Database\Seeders;

use App\Enums\Sales\PropertyStatus;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Sales\Property;
use App\Models\Sales\Block;

class PropertiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        // Get block IDs for reference
        $block279 = Block::where('name', '279')->first()->id;
        $block280 = Block::where('name', '280')->first()->id;
        $statuses = [PropertyStatus::Available, PropertyStatus::Sold, PropertyStatus::Booked, PropertyStatus::NotAvailable];
        $randomStatus = $statuses[array_rand($statuses)];

        // Property data from the provided CSV-like data
        $properties = [
            [
                'name' => '5492',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 23.03,
                'price_per_meter' => 1200,
                'price' => 27636,
                'remaining_amount' => 27636,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 11.66,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5493',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 97.37,
                'price_per_meter' => 1200,
                'price' => 116844,
                'remaining_amount' => 116844,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5494',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 173.59,
                'price_per_meter' => 1200,
                'price' => 208308,
                'remaining_amount' => 208308,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5495',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 249.82,
                'price_per_meter' => 1200,
                'price' => 299784,
                'remaining_amount' => 299784,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5496',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 326.04,
                'price_per_meter' => 1200,
                'price' => 391248,
                'remaining_amount' => 391248,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5497',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 402.27,
                'price_per_meter' => 1200,
                'price' => 482724,
                'remaining_amount' => 482724,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5498',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 449.39,
                'price_per_meter' => 1200,
                'price' => 539268,
                'remaining_amount' => 539268,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5499',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 29.1,
                'price_per_meter' => 1200,
                'price' => 34920,
                'remaining_amount' => 34920,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'جنوبي',
                'front_width' => 13.84,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5500',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 450,
                'price_per_meter' => 1200,
                'price' => 540000,
                'remaining_amount' => 540000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5501',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 104.72,
                'price_per_meter' => 1200,
                'price' => 125664,
                'remaining_amount' => 125664,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'جنوبي',
                'front_width' => 15.84,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5502',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 450,
                'price_per_meter' => 1200,
                'price' => 540000,
                'remaining_amount' => 540000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18 \ 5',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5503',
                'zone' => '6',
                'block_id' => $block279,
                'block_number' => 279,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 180.94,
                'price_per_meter' => 1200,
                'price' => 217128,
                'remaining_amount' => 217128,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18 \ 5',
                'orientation' => 'جنوبي',
                'front_width' => 15.84,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5504',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 450,
                'price_per_meter' => 1200,
                'price' => 540000,
                'remaining_amount' => 540000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18 \ 5',
                'orientation' => 'شمالي',
                'front_width' => 15.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5505',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 282.57,
                'price_per_meter' => 1200,
                'price' => 339084,
                'remaining_amount' => 339084,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18 \ 5',
                'orientation' => 'جنوبي',
                'front_width' => 15.84,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5506',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 420,
                'price_per_meter' => 1200,
                'price' => 504000,
                'remaining_amount' => 504000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 14.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5507',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 332.51,
                'price_per_meter' => 1200,
                'price' => 399012,
                'remaining_amount' => 399012,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'جنوبي',
                'front_width' => 14.78,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5508',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 420,
                'price_per_meter' => 1200,
                'price' => 504000,
                'remaining_amount' => 504000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 14.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5509',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 397.8,
                'price_per_meter' => 1200,
                'price' => 477360,
                'remaining_amount' => 477360,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'جنوبي',
                'front_width' => 14.64,
                'depth' => null,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5510',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 420,
                'price_per_meter' => 1200,
                'price' => 504000,
                'remaining_amount' => 504000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'شمالي',
                'front_width' => 14.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
            [
                'name' => '5511',
                'zone' => '6',
                'block_id' => $block280,
                'block_number' => 280,
                'property_type_detail' => 'سكني فلل',
                'status' => $randomStatus,
                'area' => 420,
                'price_per_meter' => 1200,
                'price' => 504000,
                'remaining_amount' => 504000,
                'virtual_tour_link' => 'drive google url',
                'street_width' => '18',
                'orientation' => 'جنوبي',
                'front_width' => 14.00,
                'depth' => 30.00,
                'notes' => 'Note - Random Note',
                'type' => 'land'
            ],
        ];

        // Insert all properties
        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }
    }
}
